'use client';
import { useState, useMemo } from 'react';
import { useRouter } from 'next/navigation';
import { useApp } from '@/lib/store';
import { HOURS, type TipoEvento, type Evento } from '@/types/database';
const TODAY=new Date();const TS=fmt(TODAY);
function fmt(d:Date){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');}
function addD(d:Date,n:number){const r=new Date(d);r.setDate(r.getDate()+n);return r;}
function getMon(d:Date){const r=new Date(d);r.setDate(r.getDate()-((r.getDay()+6)%7));return r;}
function dim(y:number,m:number){return new Date(y,m+1,0).getDate();}
function fdm(y:number,m:number){return(new Date(y,m,1).getDay()+6)%7;}
function dd(s:string){return s.split('-').reverse().join('/');}
function sd(d:Date){return['Dom','Lun','Mar','Mer','Gio','Ven','Sab'][d.getDay()];}
function pd(s:string){const p=s.split('-').map(Number);return new Date(p[0],p[1]-1,p[2]);}
const DI=['Lun','Mar','Mer','Gio','Ven','Sab','Dom'];
const MI=['Gennaio','Febbraio','Marzo','Aprile','Maggio','Giugno','Luglio','Agosto','Settembre','Ottobre','Novembre','Dicembre'];

export default function Cal(){
  const router=useRouter();
  const{getMyEventi,getMyEventiByDate,addEvento,updateEvento,deleteEvento,acceptEvento,commesse,team,currentUser,addCommessa}=useApp();
  const[view,setView]=useState<'day'|'week'|'month'>('week');const[sel,setSel]=useState(TS);
  const[vm,setVm]=useState({y:TODAY.getFullYear(),m:TODAY.getMonth()});const[ws,setWs]=useState(getMon(TODAY));
  const[showF,setShowF]=useState(false);const[editE,setEditE]=useState<Partial<Evento>|null>(null);
  const[detE,setDetE]=useState<Evento|null>(null);const[cfmDel,setCfmDel]=useState(false);
  const[showMenu,setShowMenu]=useState(false);
  const[showNewCm,setShowNewCm]=useState(false);
  const[cf,setCf]=useState({nome:'',cognome:'',telefono:'',indirizzo:'',citta:'',note:''});
  const[cmOk,setCmOk]=useState(false);

  const my=getMyEventi();const dayEv=getMyEventiByDate(sel);
  const eds=useMemo(()=>new Set(my.map(e=>e.data)),[my]);
  const wd=useMemo(()=>Array.from({length:7},(_,i)=>addD(ws,i)),[ws]);
  const openNew=(d?:string)=>{setEditE({data:d||sel,ora_inizio:'09:00',durata_minuti:60,tipo:'sopralluogo',stato:'confirmed',assegnato_a:currentUser.id,assegnato_da:currentUser.id,cliente_nome:'',cliente_indirizzo:'',note:'',commessa_id:null});setShowF(true);setDetE(null);setShowMenu(false);};
  const openEdit=(ev:Evento)=>{setEditE({...ev});setShowF(true);setDetE(null);};
  const saveF=()=>{if(!editE||!editE.cliente_nome||!editE.data)return;if(editE.id)updateEvento(editE.id,editE);else addEvento(editE as any);setShowF(false);setEditE(null);};
  const saveCm=()=>{
    if(!cf.nome||!cf.cognome)return;
    const cm=addCommessa({nome:cf.nome,cognome:cf.cognome,telefono:cf.telefono||null,email:null,indirizzo:cf.indirizzo||null,citta:cf.citta||null,cap:null,note:null},cf.indirizzo,cf.citta,cf.note);
    setCmOk(true);setTimeout(()=>{setCmOk(false);setShowNewCm(false);setCf({nome:'',cognome:'',telefono:'',indirizzo:'',citta:'',note:''});router.push('/commessa/'+cm.id);},800);
  };

  // Nuova Commessa form
  if(showNewCm){return(
    <div className="px-5 animate-fade-in">
      <div className="flex justify-between items-center pt-4 mb-5"><h2 className="text-xl font-bold">➕ Nuova Commessa</h2><button onClick={()=>setShowNewCm(false)} className="bg-transparent border-none text-3xl cursor-pointer" style={{color:'var(--text-muted)'}}>×</button></div>
      {cmOk?(<div className="text-center py-16"><div className="text-5xl mb-3">✅</div><div className="text-lg font-bold" style={{color:'var(--success)'}}>Commessa creata!</div></div>):(<>
        <div className="rounded-[14px] p-4 border mb-4" style={{background:'var(--surface)',borderColor:'var(--border)'}}>
          <div className="text-[11px] font-semibold uppercase tracking-wide mb-3" style={{color:'var(--accent)'}}>👤 Cliente</div>
          <div className="grid grid-cols-2 gap-2.5 mb-3">
            <div><Lb>Cognome *</Lb><input placeholder="Rossi" value={cf.cognome} onChange={e=>setCf({...cf,cognome:e.target.value})} className="w-full p-3 rounded-[10px] text-sm" style={{background:'var(--bg)',border:'1px solid var(--border)',color:'var(--text)',fontFamily:'inherit'}}/></div>
            <div><Lb>Nome *</Lb><input placeholder="Mario" value={cf.nome} onChange={e=>setCf({...cf,nome:e.target.value})} className="w-full p-3 rounded-[10px] text-sm" style={{background:'var(--bg)',border:'1px solid var(--border)',color:'var(--text)',fontFamily:'inherit'}}/></div>
          </div>
          <div><Lb>Telefono</Lb><input placeholder="333 1234567" value={cf.telefono} onChange={e=>setCf({...cf,telefono:e.target.value})} className="w-full p-3 rounded-[10px] text-sm" style={{background:'var(--bg)',border:'1px solid var(--border)',color:'var(--text)',fontFamily:'inherit'}} type="tel"/></div>
        </div>
        <div className="rounded-[14px] p-4 border mb-4" style={{background:'var(--surface)',borderColor:'var(--border)'}}>
          <div className="text-[11px] font-semibold uppercase tracking-wide mb-3" style={{color:'var(--accent)'}}>🏗️ Cantiere</div>
          <div className="mb-3"><Lb>Indirizzo</Lb><input placeholder="Via Roma 12" value={cf.indirizzo} onChange={e=>setCf({...cf,indirizzo:e.target.value})} className="w-full p-3 rounded-[10px] text-sm" style={{background:'var(--bg)',border:'1px solid var(--border)',color:'var(--text)',fontFamily:'inherit'}}/></div>
          <div className="mb-3"><Lb>Città</Lb><input placeholder="Cosenza" value={cf.citta} onChange={e=>setCf({...cf,citta:e.target.value})} className="w-full p-3 rounded-[10px] text-sm" style={{background:'var(--bg)',border:'1px solid var(--border)',color:'var(--text)',fontFamily:'inherit'}}/></div>
          <div><Lb>Note</Lb><input placeholder="Appartamento 3° piano..." value={cf.note} onChange={e=>setCf({...cf,note:e.target.value})} className="w-full p-3 rounded-[10px] text-sm" style={{background:'var(--bg)',border:'1px solid var(--border)',color:'var(--text)',fontFamily:'inherit'}}/></div>
        </div>
        <button onClick={saveCm} className="w-full py-4 rounded-[10px] text-white text-base font-bold cursor-pointer border-none mb-2" style={{background:(cf.nome&&cf.cognome)?'var(--accent)':'var(--border)',fontFamily:'inherit'}}>✓ Crea Commessa</button>
        <button onClick={()=>setShowNewCm(false)} className="w-full py-3.5 rounded-[10px] text-sm font-semibold cursor-pointer bg-transparent" style={{border:'1px solid var(--border)',color:'var(--text-muted)',fontFamily:'inherit'}}>Annulla</button>
      </>)}
    </div>
  );}

  if(detE){const mb=team.find(m=>m.id===detE.assegnato_a);const bb=team.find(m=>m.id===detE.assegnato_da);return(
    <div className="px-5 animate-fade-in"><button onClick={()=>{setDetE(null);setCfmDel(false);}} className="bg-transparent border-none text-sm font-semibold cursor-pointer py-3.5" style={{color:'var(--accent)'}}>← Calendario</button>
      <div className="rounded-[14px] p-5 border mb-4" style={{background:'var(--surface)',borderColor:'var(--border)'}}><div className="flex justify-between mb-3"><TB t={detE.tipo} lg/><SB s={detE.stato}/></div><h2 className="text-[22px] font-bold mb-1">{detE.cliente_nome}</h2><p className="text-sm mb-3" style={{color:'var(--text-muted)'}}>{detE.cliente_indirizzo}</p><div className="grid grid-cols-3 gap-2.5"><IB i="📅" l="Data" v={dd(detE.data)}/><IB i="🕐" l="Ora" v={detE.ora_inizio.slice(0,5)}/><IB i="⏱" l="Durata" v={detE.durata_minuti+'m'}/></div></div>
      <div className="rounded-[14px] p-4 border mb-4" style={{background:'var(--surface)',borderColor:'var(--border)'}}><div className="text-[11px] font-semibold uppercase tracking-wide mb-2.5" style={{color:'var(--text-muted)'}}>Assegnazione</div><div className="flex items-center gap-3 mb-2"><div className="w-9 h-9 rounded-full flex items-center justify-center text-xs font-bold text-white" style={{background:mb?.avatar_color}}>{mb?.nome[0]}{mb?.cognome[0]}</div><div><div className="text-[15px] font-semibold">{mb?.nome} {mb?.cognome}</div><div className="text-xs" style={{color:'var(--text-muted)'}}>{mb?.ruolo}</div></div></div><div className="text-xs" style={{color:'var(--text-dim)'}}>Da <span className="font-semibold" style={{color:'var(--text-muted)'}}>{bb?.nome} {bb?.cognome}</span></div></div>
      {detE.note&&<div className="rounded-[14px] p-4 border mb-4" style={{background:'var(--surface)',borderColor:'var(--border)'}}><div className="text-[11px] font-semibold uppercase mb-1.5" style={{color:'var(--text-muted)'}}>Note</div><div className="text-sm">{detE.note}</div></div>}
      <div className="flex flex-col gap-2">{detE.stato==='pending'&&<Bt p onClick={()=>{acceptEvento(detE.id);setDetE({...detE,stato:'confirmed'})}}>✓ Accetta</Bt>}<Bt onClick={()=>openEdit(detE)}>✏️ Modifica</Bt>{detE.commessa_id&&<Bt onClick={()=>{window.location.href='/commessa/'+detE.commessa_id}}>📂 Commessa</Bt>}
        {!cfmDel?<Bt onClick={()=>setCfmDel(true)} style={{borderColor:'rgba(231,76,60,0.3)',color:'var(--danger)'}}>🗑 Elimina</Bt>:(<div className="rounded-[10px] p-3.5 text-center" style={{background:'rgba(231,76,60,0.08)',border:'1px solid rgba(231,76,60,0.3)'}}><div className="text-sm font-semibold mb-2.5" style={{color:'var(--danger)'}}>Confermi?</div><div className="flex gap-2"><button onClick={()=>{deleteEvento(detE.id);setDetE(null);setCfmDel(false);}} className="flex-1 py-2.5 border-none rounded-lg text-white text-[13px] font-bold cursor-pointer" style={{background:'var(--danger)',fontFamily:'inherit'}}>Sì</button><button onClick={()=>setCfmDel(false)} className="flex-1 py-2.5 rounded-lg text-[13px] font-semibold cursor-pointer" style={{background:'var(--surface)',border:'1px solid var(--border)',color:'var(--text-muted)',fontFamily:'inherit'}}>No</button></div></div>)}</div></div>);}

  if(showF&&editE){const isE=!!editE.id;const se=(k:string,v:any)=>setEditE(p=>p?{...p,[k]:v}:null);return(
    <div className="px-5 animate-fade-in"><div className="flex justify-between items-center mb-5 pt-4"><h2 className="text-xl font-bold">{isE?'✏️ Modifica':'➕ Nuovo'} Appuntamento</h2><button onClick={()=>{setShowF(false);setEditE(null);}} className="bg-transparent border-none text-3xl cursor-pointer" style={{color:'var(--text-muted)'}}>×</button></div>
      <div className="mb-3.5"><Lb>Tipo</Lb><div className="flex gap-2">{(['sopralluogo','misure'] as TipoEvento[]).map(t=>(<button key={t} onClick={()=>se('tipo',t)} className="flex-1 py-3 rounded-[10px] text-sm font-bold cursor-pointer" style={{background:editE.tipo===t?'var(--accent-soft)':'var(--surface)',border:'2px solid '+(editE.tipo===t?'var(--accent)':'var(--border)'),color:editE.tipo===t?'var(--accent)':'var(--text-muted)',fontFamily:'inherit'}}>{t==='sopralluogo'?'📍 Sopralluogo':'📐 Misure'}</button>))}</div></div>
      <div className="grid grid-cols-2 gap-2.5 mb-3.5"><div><Lb>Data</Lb><input type="date" value={editE.data||''} onChange={e=>se('data',e.target.value)} className="w-full p-3 rounded-[10px] text-sm" style={{background:'var(--bg)',border:'1px solid var(--border)',color:'var(--text)',colorScheme:'dark',fontFamily:'inherit'}}/></div><div><Lb>Ora</Lb><select value={editE.ora_inizio||'09:00'} onChange={e=>se('ora_inizio',e.target.value)} className="w-full p-3 rounded-[10px] text-sm" style={{background:'var(--bg)',border:'1px solid var(--border)',color:'var(--text)',colorScheme:'dark',fontFamily:'inherit'}}>{HOURS.map(h=><option key={h} value={h}>{h}</option>)}</select></div></div>
      <div className="mb-3.5"><Lb>Durata</Lb><div className="flex gap-1.5">{[30,60,90,120].map(d=>(<button key={d} onClick={()=>se('durata_minuti',d)} className="flex-1 py-2.5 rounded-lg text-[13px] font-bold cursor-pointer" style={{background:editE.durata_minuti===d?'var(--accent)':'var(--surface)',border:'1px solid '+(editE.durata_minuti===d?'var(--accent)':'var(--border)'),color:editE.durata_minuti===d?'#fff':'var(--text-muted)',fontFamily:'inherit'}}>{d}m</button>))}</div></div>
      <FI l="Cliente" v={editE.cliente_nome||''} s={v=>se('cliente_nome',v)} ph="Nome..."/><FI l="Indirizzo" v={editE.cliente_indirizzo||''} s={v=>se('cliente_indirizzo',v)} ph="Via..."/>
      <div className="mb-3.5"><Lb>Commessa</Lb><select value={editE.commessa_id||''} onChange={e=>{const id=e.target.value||null;se('commessa_id',id);if(id){const c=commesse.find(x=>x.id===id);if(c?.cliente){se('cliente_nome',c.cliente.cognome+' '+c.cliente.nome);se('cliente_indirizzo',(c.indirizzo_cantiere||'')+', '+(c.citta_cantiere||''));}}}} className="w-full p-3 rounded-[10px] text-sm" style={{background:'var(--bg)',border:'1px solid var(--border)',color:'var(--text)',colorScheme:'dark',fontFamily:'inherit'}}><option value="">— Nessuna —</option>{commesse.map(c=><option key={c.id} value={c.id}>{c.codice} — {c.cliente?c.cliente.cognome+' '+c.cliente.nome:''}</option>)}</select></div>
      <div className="mb-3.5"><Lb>Assegna a</Lb><div className="grid grid-cols-2 gap-2">{team.filter(m=>m.ruolo!=='ufficio').map(m=>(<button key={m.id} onClick={()=>se('assegnato_a',m.id)} className="flex items-center gap-2.5 p-2.5 rounded-[10px] cursor-pointer" style={{background:editE.assegnato_a===m.id?'color-mix(in srgb, '+m.avatar_color+' 12%, transparent)':'var(--surface)',border:'2px solid '+(editE.assegnato_a===m.id?m.avatar_color:'var(--border)'),fontFamily:'inherit'}}><div className="w-8 h-8 rounded-full flex items-center justify-center text-[11px] font-bold text-white" style={{background:m.avatar_color}}>{m.nome[0]}{m.cognome[0]}</div><div className="text-left"><div className="text-[13px] font-semibold">{m.nome}</div><div className="text-[10px]" style={{color:'var(--text-muted)'}}>{m.ruolo}</div></div></button>))}</div></div>
      <FI l="Note" v={editE.note||''} s={v=>se('note',v)} ph="Note..."/>
      <button onClick={saveF} className="w-full py-4 rounded-[10px] text-white text-base font-bold cursor-pointer border-none mb-2" style={{background:(editE.cliente_nome&&editE.data)?'var(--accent)':'var(--border)',fontFamily:'inherit'}}>{isE?'💾 Salva':'✓ Crea'}</button>
      <button onClick={()=>{setShowF(false);setEditE(null);}} className="w-full py-3.5 rounded-[10px] text-sm font-semibold cursor-pointer bg-transparent" style={{border:'1px solid var(--border)',color:'var(--text-muted)',fontFamily:'inherit'}}>Annulla</button></div>);}

  return(<div className="px-5"><div className="pt-4 pb-2"><div className="text-[11px] font-semibold tracking-[2px] uppercase flex items-center gap-1.5" style={{color:'var(--accent)'}}><span className="inline-block w-2 h-2 rounded-full" style={{background:'var(--accent)',boxShadow:'0 0 8px var(--accent)'}}/>CALENDARIO</div></div>
    <div className="flex p-[3px] mb-4 rounded-[10px]" style={{background:'var(--surface)',border:'1px solid var(--border)'}}>{([{v:'day',l:'Giorno'},{v:'week',l:'Settimana'},{v:'month',l:'Mese'}] as const).map(x=>(<button key={x.v} onClick={()=>setView(x.v)} className="flex-1 py-2.5 rounded-lg border-none text-[13px] font-bold cursor-pointer" style={{background:view===x.v?'var(--accent)':'transparent',color:view===x.v?'#fff':'var(--text-muted)',fontFamily:'inherit'}}>{x.l}</button>))}</div>
    {view==='month'&&(<><div className="flex justify-between items-center mb-3.5"><NB onClick={()=>setVm(v=>v.m===0?{y:v.y-1,m:11}:{y:v.y,m:v.m-1})}>‹</NB><h2 className="text-lg font-bold">{MI[vm.m]} {vm.y}</h2><NB onClick={()=>setVm(v=>v.m===11?{y:v.y+1,m:0}:{y:v.y,m:v.m+1})}>›</NB></div><div className="grid grid-cols-7 gap-0.5 mb-1.5">{DI.map(d=><div key={d} className="text-center text-[11px] font-semibold py-1" style={{color:'var(--text-dim)'}}>{d}</div>)}</div><div className="grid grid-cols-7 gap-0.5 mb-4">{Array.from({length:fdm(vm.y,vm.m)},(_,i)=><div key={'e'+i}/>)}{Array.from({length:dim(vm.y,vm.m)},(_,i)=>{const day=i+1;const ds=vm.y+'-'+String(vm.m+1).padStart(2,'0')+'-'+String(day).padStart(2,'0');const it=ds===TS,is=ds===sel,he=eds.has(ds);return<button key={day} onClick={()=>setSel(ds)} className="aspect-square rounded-[10px] border text-sm cursor-pointer relative flex flex-col items-center justify-center" style={{background:is?'var(--accent)':it?'var(--accent-soft)':'transparent',borderColor:it&&!is?'rgba(255,107,43,0.4)':'transparent',color:is?'#fff':it?'var(--accent)':'var(--text)',fontWeight:it||is?700:500,fontFamily:'inherit'}}>{day}{he&&<div className="w-[5px] h-[5px] rounded-full absolute bottom-1" style={{background:is?'#fff':'var(--accent)'}}/>}</button>;})}</div></>)}
    {view==='week'&&(<><div className="flex justify-between items-center mb-3.5"><NB onClick={()=>setWs(w=>addD(w,-7))}>‹</NB><h2 className="text-base font-bold">{dd(fmt(wd[0]))+' — '+dd(fmt(wd[6]))}</h2><NB onClick={()=>setWs(w=>addD(w,7))}>›</NB></div><div className="grid grid-cols-7 gap-1 mb-4">{wd.map(d=>{const ds=fmt(d),it=ds===TS,is=ds===sel,he=eds.has(ds);return<button key={ds} onClick={()=>setSel(ds)} className="py-2.5 px-1 rounded-[10px] text-center cursor-pointer" style={{background:is?'var(--accent)':it?'var(--accent-soft)':'var(--surface)',border:'1px solid '+(is?'var(--accent)':'var(--border)'),fontFamily:'inherit'}}><div className="text-[10px] font-semibold mb-1" style={{color:is?'#fff':'var(--text-dim)'}}>{sd(d)}</div><div className="text-base font-bold" style={{color:is?'#fff':it?'var(--accent)':'var(--text)'}}>{d.getDate()}</div>{he&&<div className="w-[5px] h-[5px] rounded-full mx-auto mt-1" style={{background:is?'#fff':'var(--accent)'}}/>}</button>;})}</div></>)}
    {view==='day'&&(<div className="flex justify-between items-center mb-3.5"><NB onClick={()=>setSel(fmt(addD(pd(sel),-1)))}>‹</NB><h2 className="text-lg font-bold">{(sel===TS?'Oggi ':'')+sd(pd(sel))+' '+dd(sel)}</h2><NB onClick={()=>setSel(fmt(addD(pd(sel),1)))}>›</NB></div>)}
    <div className="flex justify-between items-center mb-2.5"><h3 className="text-sm font-bold">{view==='day'?'Appuntamenti':(sel===TS?'Oggi':dd(sel))}</h3><span className="text-xs" style={{color:'var(--text-dim)'}}>{dayEv.length} app.</span></div>
    {dayEv.length>0?dayEv.map(ev=>(<button key={ev.id} onClick={()=>setDetE(ev)} className="w-full text-left cursor-pointer rounded-[10px] p-3 border mb-2" style={{background:'var(--surface)',borderColor:'var(--border)',borderLeft:'3px solid '+(ev.stato==='confirmed'?'var(--success)':'var(--warning)'),fontFamily:'inherit'}}><div className="flex justify-between items-start"><div><div className="flex items-center gap-2 mb-1"><span className="font-mono text-sm font-bold" style={{color:'var(--accent)'}}>{ev.ora_inizio.slice(0,5)}</span><TB t={ev.tipo}/></div><div className="text-[15px] font-semibold mb-0.5">{ev.cliente_nome}</div><div className="text-xs" style={{color:'var(--text-muted)'}}>{ev.cliente_indirizzo}</div></div><SB s={ev.stato}/></div></button>)):(<div className="rounded-[14px] py-7 border text-center" style={{background:'var(--surface)',borderColor:'var(--border)',color:'var(--text-dim)'}}>Nessun appuntamento</div>)}

    {showMenu&&<div className="fixed inset-0 z-40" onClick={()=>setShowMenu(false)}/>}
    {showMenu&&(<div className="fixed bottom-[170px] z-50 flex flex-col gap-2 animate-fade-in" style={{right:'calc(50% - 195px)'}}>
      <button onClick={()=>{openNew(sel);}} className="flex items-center gap-2.5 py-3 px-4 rounded-[12px] text-sm font-bold cursor-pointer border-none text-white" style={{background:'var(--accent)',fontFamily:'inherit',boxShadow:'0 4px 20px var(--accent-glow)'}}>📅 Nuovo Appuntamento</button>
      <button onClick={()=>{setShowNewCm(true);setShowMenu(false);}} className="flex items-center gap-2.5 py-3 px-4 rounded-[12px] text-sm font-bold cursor-pointer border" style={{background:'var(--surface)',borderColor:'var(--accent)',color:'var(--accent)',fontFamily:'inherit',boxShadow:'0 4px 20px rgba(0,0,0,0.3)'}}>📂 Nuova Commessa</button>
    </div>)}
    <button onClick={()=>setShowMenu(!showMenu)} className="fixed bottom-[100px] w-14 h-14 rounded-full border-none text-white text-[26px] cursor-pointer flex items-center justify-center z-50 transition-transform" style={{right:'calc(50% - 195px)',background:'var(--accent)',boxShadow:'0 8px 32px var(--accent-glow)',transform:showMenu?'rotate(45deg)':'none'}}>{showMenu?'+':'+'}</button>
  </div>);
}

function TB({t,lg}:{t:string;lg?:boolean}){const c=t==='misure'?{l:'Misure',c:'var(--accent)',i:'📐'}:{l:'Sopralluogo',c:'var(--info)',i:'📍'};return<span className={(lg?'text-sm py-1.5 px-3':'text-[11px] py-0.5 px-2')+' font-semibold rounded-2xl'} style={{background:'color-mix(in srgb, '+c.c+' 15%, transparent)',color:c.c}}>{c.i} {c.l}</span>;}
function SB({s}:{s:string}){const v=s==='confirmed'?{l:'Confermato',c:'var(--success)'}:{l:'In attesa',c:'var(--warning)'};return<span className="text-[10px] font-bold py-0.5 px-2 rounded-xl uppercase" style={{background:'color-mix(in srgb, '+v.c+' 15%, transparent)',color:v.c}}>{v.l}</span>;}
function IB({i,l,v}:{i:string;l:string;v:string}){return<div className="rounded-[10px] py-2.5 px-2 text-center" style={{background:'var(--bg)'}}><div className="text-[10px] mb-0.5" style={{color:'var(--text-dim)'}}>{i} {l}</div><div className="text-sm font-bold font-mono">{v}</div></div>;}
function NB({onClick,children}:{onClick:()=>void;children:React.ReactNode}){return<button onClick={onClick} className="w-[38px] h-[38px] rounded-[10px] text-xl font-semibold cursor-pointer flex items-center justify-center" style={{background:'var(--surface)',border:'1px solid var(--border)',color:'var(--text)',fontFamily:'inherit'}}>{children}</button>;}
function Bt({children,onClick,p,style}:{children:React.ReactNode;onClick?:()=>void;p?:boolean;style?:React.CSSProperties}){return<button onClick={onClick} className={'w-full py-3.5 rounded-[10px] text-sm font-semibold cursor-pointer '+(p?'text-white border-none':'border')} style={{background:p?'var(--accent)':'var(--surface)',borderColor:'var(--border)',color:p?undefined:'var(--text)',fontFamily:'inherit',...style}}>{children}</button>;}
function Lb({children}:{children:React.ReactNode}){return<label className="block text-[11px] font-semibold mb-1.5" style={{color:'var(--text-muted)'}}>{children}</label>;}
function FI({l,v,s,ph}:{l:string;v:string;s:(v:string)=>void;ph:string}){return<div className="mb-3.5"><Lb>{l}</Lb><input placeholder={ph} value={v} onChange={e=>s(e.target.value)} className="w-full p-3 rounded-[10px] text-sm" style={{background:'var(--bg)',border:'1px solid var(--border)',color:'var(--text)',fontFamily:'inherit'}}/></div>;}
